"""Build analysis-ready datasets from data/ into processed/ (not committed; rebuild any time).

  python -m processing.build us --areas ERCO,CISO,PJM --start 2019-01-01
  python -m processing.build europe --areas DE,FR
  python -m processing.build aemo
  python -m processing.build chotot
  python -m processing.build all
Updates processed/quality.csv and processed/QUALITY.md with, for every screened series: hours, raw missing %,
points flagged by each check and missing % after cleaning (before short-gap interpolation). Rows of areas that
are not rebuilt are kept, so building one grid never erases the others.
"""
import argparse
import json

import pandas as pd

from processing import energy, realestate
from processing.io import output_dir

DEFAULT_US = ["CISO", "ERCO", "NYIS", "PJM", "MISO", "ISNE", "SWPP", "BPAT", "SOCO", "FPL", "DUK", "TVA",
              "AZPS", "PSCO", "NEVP", "SCL"]
DEFAULT_EU = list(energy.EU_PRICE_ZONE)


def write_report(rows, extra):
    table = output_dir() / "quality.csv"
    df = pd.DataFrame(rows)
    if table.exists():
        old = pd.read_csv(table)
        if not df.empty:
            done = old.set_index(["grid", "area", "series"]).index.isin(df.set_index(["grid", "area", "series"]).index)
            old = old[~done]
        df = pd.concat([old, df], ignore_index=True)
    if not df.empty:
        df = df.sort_values(["grid", "area", "series"])
        df.to_csv(table, index=False)
    lines = ["# Data quality report", "", "Generated by `python -m processing.build`.", ""]
    if not df.empty:
        lines += ["| " + " | ".join(df.columns) + " |", "|" + "---|" * len(df.columns)]
        lines += ["| " + " | ".join(str(v) for v in r) + " |" for r in df.itertuples(index=False)]
    summary_path = output_dir() / "chotot" / "summary.json"
    if extra:
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.write_text(json.dumps(extra, ensure_ascii=False), encoding="utf-8")
    elif summary_path.exists():
        extra = json.loads(summary_path.read_text(encoding="utf-8"))
    for name, summary in extra.items():
        lines += ["", f"## {name}", "", *[f"- {k}: {v}" for k, v in summary.items()]]
    path = output_dir() / "QUALITY.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"report -> {path}")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("target", choices=["us", "europe", "aemo", "chotot", "all"])
    ap.add_argument("--areas", help="comma list of BAs (us) or country codes (europe); not with 'all'")
    ap.add_argument("--start")
    ap.add_argument("--end")
    ap.add_argument("--max-gap", type=int, default=3, help="interpolate gaps up to this many hours")
    args = ap.parse_args(argv)
    if args.areas and args.target == "all":
        ap.error("--areas needs a single grid (us or europe)")
    areas = args.areas.split(",") if args.areas else None
    report, extra = [], {}
    builds = {"us": lambda r: energy.build_us(areas or DEFAULT_US, args.start, args.end, r, args.max_gap),
              "europe": lambda r: energy.build_europe(areas or DEFAULT_EU, args.start, args.end, r, args.max_gap),
              "aemo": lambda r: energy.build_aemo(args.start, args.end, r, args.max_gap)}
    for grid, build in builds.items():
        if args.target in (grid, "all"):
            rows = []
            build(rows)
            report += [{"grid": grid, **row} for row in rows]
    if args.target in ("chotot", "all"):
        _, summary = realestate.clean_chotot()
        extra["Chợ Tốt listings"] = summary
    write_report(report, extra)


if __name__ == "__main__":
    main()
